public class Main {
    public static void main() {
        Chihuahua chihuahua = new Chihuahua(1.5, 2.0);
        BlackBear blackBear = new BlackBear(6.5, 4.0);
        Koala koala = new Koala(3.5);
        Anaconda anaconda = new Anaconda("Dark Green", 5.0);
        Gecko gecko = new Gecko("Cyan", 0.7);
        BeardedDragon beardedDragon = new BeardedDragon(4.2);
        BoxTurtle boxTurtle = new BoxTurtle(2.1);
        BaskingShark baskingShark = new BaskingShark("Oceans", 10.5);
        TigerShark tigerShark = new TigerShark("Tropical Reefs", 12);
        Octopus octo = new Octopus(8, 110);
        Nautilus nauti = new Nautilus(90, 15.0);
        Scorpion scorp = new Scorpion(true, 3.0);
        Spider spid = new Spider(true, 2.2);
        chihuahua.setEyeSize(3.2);
        blackBear.setHibernationDuration(5.5);
        anaconda.setCoilLength(7.3);
        gecko.setGripStrength(1.4);
        baskingShark.setGillRakerLength(14.8);
        tigerShark.setStripeCount(18);
        octo.setIq(135);
        nauti.setShellDiameter(22.5);
        scorp.setPincerSize(4.6);
        spid.setLegLength(3.1);

        IO.println("--- THE GRAND CHRONICLES OF NATURE ---");
        IO.println("");
        IO.println("Beneath the safety of a domestic homestead, an attentive Chihuahua keeps watch. ");
        IO.println("Possessing an expressive eye size of " + chihuahua.getEyeSize() + " cm and a coat fur length of " + chihuahua.getFurLength() + " cm, it springs into action.");
        chihuahua.wagTail();
        chihuahua.communicate();
        IO.println("Deep within the neighboring mountains, a wild Black Bear wanders out after a prolonged winter rest ");
        IO.println("that required " + blackBear.getHibernationDuration() + " months of deep sleep inside a secure cave with its " + blackBear.getFurLength() + " cm protective coat.");
        blackBear.climbTree();
        blackBear.navigateTrees();
        blackBear.communicate();
        IO.println("High up in a nearby eucalyptus grove, a quiet Koala navigates the dense canopy. ");
        IO.println("Relying on strong sharp claws measuring " + koala.getClawLength() + " cm, it handles high branches safely.");
        koala.navigateTrees();
        IO.println("");
        IO.println("In the dark leaf litter below, stealthy micro-predators deploy their unique structural traits. ");
        IO.println("A crawling Spider balances its weight smoothly, shifting its long " + spid.getLegLength() + " cm legs over a web framework (Venom Status: " + spid.checkVenom() + ").");
        spid.makeWebs();
        spid.capturePrey();
        spid.injectVenom();
        IO.println("From a nearby sandy burrow, a fierce Scorpion emerges, brandishing heavy claws that reach a size of " + scorp.getPincerSize() + " cm (Venom Status: " + scorp.checkVenom() + ").");
        scorp.burrow();
        scorp.capturePrey();
        scorp.injectVenom();
        IO.println("");
        IO.println("Along the warm, sunlit riverbank rocks, ancient cold-blooded behaviors manifest. ");
        IO.println("A Bearded Dragon positions itself flat against the stone matrix, showing off a skin roughness index of " + beardedDragon.getScaleRoughness() + ".");
        beardedDragon.regulateTemperature();
        IO.println("Seeking a cooler shade profile, a mature Box Turtle pulls inside its defensive barrier, built with a thickness of " + boxTurtle.getShellThickness() + " cm.");
        boxTurtle.regulateTemperature();
        IO.println("Scouting the mossy branches above, a brilliant Gecko displaying a vivid " + gecko.getScaleColor() + " hue relies on a feet grip strength of " + gecko.getGripStrength() + " N.");
        gecko.climbWall();
        gecko.hunt();
        gecko.Regenerate();
        IO.println("Slipping gracefully into the dark river waters, an imposing Anaconda shows off its bright " + anaconda.getScaleColor() + " scales ");
        IO.println("and tightens its immense muscles, which create massive coil loops extending " + anaconda.getCoilLength() + " meters long.");
        anaconda.dive();
        anaconda.hunt();
        anaconda.nightAction();
        IO.println("");
        IO.println("The narrative finally plunges beneath the cresting salt waves where the ocean giants rule. ");
        IO.println("An Octopus navigates an intricate coral labyrinth with its complex bundle of " + octo.getTentacleCount() + " flexible arms, ");
        IO.println("relying on a high problem-solving capacity measured at an IQ of " + octo.getIq() + ".");
        octo.propel();
        octo.grab();
        octo.defense();
        octo.Regenerate();
        IO.println("Drifting through the exact same deep waters, a unique Nautilus moves via buoyancy control. ");
        IO.println("It protects its soft body inside an elegant spiral shell featuring a diameter of " + nauti.getShellDiameter() + " cm, maneuvering with its " + nauti.getTentacleCount() + " tentacles.");
        nauti.migrate();
        nauti.propel();
        nauti.defense();
        IO.println("Patrolling the open water column of the " + baskingShark.getTypeOfHabitat() + ", a peaceful Basking Shark filters nutrients ");
        IO.println("efficiently using specialized internal gill rakers measuring " + baskingShark.getGillRakerLength() + " cm long.");
        baskingShark.stayBuoyant();
        baskingShark.swim();
        baskingShark.filterWater();
        IO.println("In contrast, a predatory Tiger Shark cruises through the waters of its " + tigerShark.getTypeOfHabitat() + " habitat, ");
        IO.println("its approach shielded by its distinct camouflage pattern of " + tigerShark.getStripeCount() + " vertical dark stripes.");
        tigerShark.stayBuoyant();
        tigerShark.swim();
        tigerShark.detectElectricity();
        tigerShark.nightAction();
        IO.println("");
        IO.println("--- END OF NARRATIVE ---");
    }
}